"""fix_relationship_names

Revision ID: 1531c9b357f6
Revises: ecf38a4b58a0
Create Date: 2025-08-21 17:09:23.950841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1531c9b357f6'
down_revision = 'ecf38a4b58a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_column('data_lancamento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_lancamento', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
