"""empty message

Revision ID: ecf38a4b58a0
Revises: 
Create Date: 2025-08-21 17:07:22.776482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf38a4b58a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sede', sa.String(length=100), nullable=False),
    sa.Column('ceo', sa.String(length=100), nullable=False),
    sa.Column('fundacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresa_nome'), ['nome'], unique=True)

    op.create_table('genero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('jogo',
    sa.Column('id_jogo', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('id_empresa', sa.Integer(), nullable=False),
    sa.Column('lancamento', sa.DateTime(), nullable=False),
    sa.Column('faixa_etaria', sa.String(length=10), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('data_lancamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_jogo')
    )
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jogo_id_empresa'), ['id_empresa'], unique=False)
        batch_op.create_index(batch_op.f('ix_jogo_nome'), ['nome'], unique=False)

    op.create_table('jogo_genero',
    sa.Column('jogo_id', sa.Integer(), nullable=False),
    sa.Column('genero_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genero_id'], ['genero.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jogo_id'], ['jogo.id_jogo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jogo_id', 'genero_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jogo_genero')
    with op.batch_alter_table('jogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jogo_nome'))
        batch_op.drop_index(batch_op.f('ix_jogo_id_empresa'))

    op.drop_table('jogo')
    op.drop_table('genero')
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresa_nome'))

    op.drop_table('empresa')
    # ### end Alembic commands ###
